;(function(w){

	w.RELANG = {},

	w.RELANG.ptbr = {
		html: 'HTML',
		align_left:	'Alinhar texto à esquerda',
		video: 'Inserir Vídeo',
		image: 'Inserir Imagem',
		table: 'Tabela',
		link: 'Link',
		link_insert: 'Inserir link',
		unlink: 'Retirar Link',
		formatting: 'Formatação',
		paragraph: 'Parágrafo',
		quote: 'Quote',
		code: 'Code',
		header1: 'Título 1',
		header2: 'Título 2',
		header3: 'Título 3',
		header4: 'Título 4',
		bold:  'Negrito',
		italic: 'Itálico',
		fontcolor: 'Cor da Fonte',
		backcolor: 'Cor de Fundo',
		unorderedlist: 'Lista Desordenada',
		orderedlist: 'Lista Ordenada',
		outdent: 'Desindentar',
		indent: 'Indentar',
		cancel: 'Cancelar',
		insert: 'Inserir',
		save: 'Salvar',
		_delete: 'Deletar',
		insert_table: 'Inserir Tabela',
		insert_row_above: 'Adicionar Linha Acima',
		insert_row_below: 'Adicionar Linha Abaixo',
		insert_column_left: 'Adicionar Coluna à Esquerda',
		insert_column_right: 'Adicionar Coluna à Direita',
		delete_column: 'Deletar Coluna',
		delete_row: 'Deletar Linha',
		delete_table: 'Deletar Tabela',
		rows: 'Linhas',
		columns: 'Colunas',
		add_head: 'Adicionar Cabeçalho',
		delete_head: 'Deletar Cabeçalho',
		title: 'Título',
		image_position: 'Posição',
		none: 'Nenhum',
		left: 'Esquerda',
		right: 'Direita',
		image_web_link: 'Link de Imagem',
		text: 'Texto',
		mailto: 'Email',
		web: 'URL',
		video_html_code: 'Código de Vídeo Incorporado',
		file: 'Inserir Arquivo',
		upload: 'Upload',
		download: 'Download',
		choose: 'Escolha',
		or_choose: 'Ou escolha',
		drop_file_here: 'Arraste o arquivo para cá',
		align_center: 'Centralizar Texto',
		align_right: 'Alinha Texto à Direita',
		align_justify: 'Justificar Texto',
		horizontalrule: 'Inserir Linha Horizontal',
		deleted: 'Deletado',
		anchor: 'Âncora (Link)',
		link_new_tab: 'Abrir link em uma nova aba',
		underline: 'Underline',
		alignment: 'Alinhamento'
	}

})(window)